"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 21:57:44.850816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('broker', sa.String(length=40), nullable=False),
    sa.Column('account_number_masked', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_price_cache_key')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sources', sa.String(length=200), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('merged', sa.Integer(), nullable=False),
    sa.Column('trades_built', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_trades', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('merged', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('synced_through', sa.DateTime(), nullable=True),
    sa.Column('earliest_reached', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', name='uq_source_account')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('time_known', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('open_quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=16), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setup', sa.String(length=80), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_underlying'), ['underlying'], unique=False)

    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('match_key', sa.String(length=200), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('time_known', sa.Boolean(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('position_effect', sa.String(length=8), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'external_id', name='uq_exec_source_ext')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_exec_account_symbol', ['account_id', 'symbol'], unique=False)
        batch_op.create_index('ix_exec_match', ['account_id', 'match_key'], unique=False)

    op.create_table('trade_tags',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id', 'tag_id')
    )
    op.create_table('trade_fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('role', sa.String(length=6), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_fills_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_fills_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_fills_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trade_fills_execution_id'))

    op.drop_table('trade_fills')
    op.drop_table('trade_tags')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index('ix_exec_match')
        batch_op.drop_index('ix_exec_account_symbol')

    op.drop_table('executions')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_underlying'))
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_opened_at'))
        batch_op.drop_index(batch_op.f('ix_trades_closed_at'))
        batch_op.drop_index(batch_op.f('ix_trades_account_id'))

    op.drop_table('trades')
    op.drop_table('source_state')
    op.drop_table('import_batches')
    op.drop_table('tags')
    op.drop_table('sync_runs')
    op.drop_table('price_cache')
    op.drop_table('oauth_tokens')
    op.drop_table('app_state')
    op.drop_table('accounts')
    # ### end Alembic commands ###
